import SectionReveal from "./SectionReveal";
import ProjectCard from "./ProjectCard";
import projects from "../../project-data";

export default function Projects() {
  return (
    <SectionReveal id="projects" kicker="// 03" title="Projects | The Databaseless Grid">
      <p className="max-w-3xl text-slate-300">
        This section is generated by mapping over the flat-file array in{" "}
        <code className="font-tech text-terminal">project-data.js</code>.
      </p>

      <div className="mt-8 grid gap-6 sm:grid-cols-2 xl:grid-cols-3">
        {projects.map((project) => (
          <ProjectCard key={project.title} project={project} />
        ))}
      </div>
    </SectionReveal>
  );
}
